import React from 'react';

export const ResourcesPage: React.FC = () => {
  return (
    <div className="container mx-auto px-4 py-12">
      <div className="max-w-4xl mx-auto">
        <h2 className="text-3xl font-bold text-slate-900 mb-8">Financial Resources</h2>
        
        <div className="grid md:grid-cols-2 gap-8">
          <div className="space-y-8">
            <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
              <h3 className="text-xl font-bold text-slate-800 mb-4"><i className="fa-solid fa-book-open text-blue-600 mr-2"></i> Essential Reading</h3>
              <ul className="space-y-3">
                <li><a href="#" className="text-slate-600 hover:text-blue-600 transition-colors flex items-center"><i className="fa-solid fa-chevron-right text-xs mr-2"></i> How to Build an Emergency Fund</a></li>
                <li><a href="#" className="text-slate-600 hover:text-blue-600 transition-colors flex items-center"><i className="fa-solid fa-chevron-right text-xs mr-2"></i> Understanding Compound Interest</a></li>
                <li><a href="#" className="text-slate-600 hover:text-blue-600 transition-colors flex items-center"><i className="fa-solid fa-chevron-right text-xs mr-2"></i> 401(k) vs. IRA: What's the Difference?</a></li>
                <li><a href="#" className="text-slate-600 hover:text-blue-600 transition-colors flex items-center"><i className="fa-solid fa-chevron-right text-xs mr-2"></i> Debt Snowball vs. Avalanche Method</a></li>
              </ul>
            </div>

            <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
               <h3 className="text-xl font-bold text-slate-800 mb-4"><i className="fa-solid fa-landmark text-blue-600 mr-2"></i> Useful Links</h3>
               <div className="space-y-3">
                  <a href="#" className="block p-3 bg-slate-50 rounded hover:bg-slate-100 transition-colors">
                     <div className="font-semibold text-slate-800">Internal Revenue Service (IRS)</div>
                     <div className="text-sm text-slate-500">Official US tax information and forms.</div>
                  </a>
                  <a href="#" className="block p-3 bg-slate-50 rounded hover:bg-slate-100 transition-colors">
                     <div className="font-semibold text-slate-800">Consumer Financial Protection Bureau</div>
                     <div className="text-sm text-slate-500">Tools and answers for money questions.</div>
                  </a>
               </div>
            </div>
          </div>

          <div className="space-y-8">
            <div className="bg-gradient-to-br from-blue-600 to-indigo-700 rounded-xl p-8 text-white">
               <h3 className="text-2xl font-bold mb-4">Financial Glossary</h3>
               <div className="space-y-4">
                  <div>
                     <div className="font-bold text-blue-100">Amortization</div>
                     <div className="text-sm text-blue-200">The process of spreading out a loan into a series of fixed payments over time.</div>
                  </div>
                  <div>
                     <div className="font-bold text-blue-100">APR (Annual Percentage Rate)</div>
                     <div className="text-sm text-blue-200">The yearly interest generated by a sum that's charged to borrowers or paid to investors.</div>
                  </div>
                  <div>
                     <div className="font-bold text-blue-100">Asset Allocation</div>
                     <div className="text-sm text-blue-200">An investment strategy that aims to balance risk and reward by apportioning a portfolio's assets according to an individual's goals.</div>
                  </div>
               </div>
               <button className="mt-6 w-full py-2 bg-white/10 hover:bg-white/20 rounded text-sm font-semibold transition-colors">View Full Glossary</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};